server:
    port: 9000

management: 
    security: 
        enabled: false
zuul:
  prefix: /idle/api
  routes:
    friend:
        path: /friend/**
        sensitiveHeaders:
        serviceId: player-service
        stripPrefix: false
    actionEffectTypes:
        path: /actionEffectTypes/**
        sensitiveHeaders:
        serviceId: hero-service
        stripPrefix: false
    heroTypes:
        path: /heroTypes/**
        sensitiveHeaders:
        serviceId: hero-service
        stripPrefix: false
    heroTypeTypes:
        path: /heroTypeTypes/**
        sensitiveHeaders:
        serviceId: hero-service
        stripPrefix: false
    heroType:
        path: /heroType/**
        sensitiveHeaders:
        serviceId: hero-service
        stripPrefix: false
    hero:
        path: /hero/**
        sensitiveHeaders:
        serviceId: hero-service
        stripPrefix: false
    battleHero:
        path: /battleHero/**
        sensitiveHeaders:
        serviceId: battle-service
        stripPrefix: false
    formation:
        path: /formation/**
        sensitiveHeaders:
        serviceId: battle-service
        stripPrefix: false
    user:
        path: /user/**
        sensitiveHeaders:
        serviceId: player-service
        stripPrefix: false
    userResource:
        path: /userResource/**
        sensitiveHeaders:
        serviceId: player-service
        stripPrefix: false
    mail:
        path: /mail/**
        sensitiveHeaders:
        serviceId: mail-service
        stripPrefix: false
    battle:
        path: /battle/**
        sensitiveHeaders:
        serviceId: battle-service
        stripPrefix: false
    shop:
        path: /shop/**
        sensitiveHeaders:
        serviceId: shop-service
        stripPrefix: false
    chat:
        path: /chat/**
        sensitiveHeaders:
        serviceId: chat-service
        stripPrefix: false
    pvp:
        path: /pvp/**
        sensitiveHeaders:
        serviceId: player-service
        stripPrefix: false
    guild:
        path: /guild/**
        sensitiveHeaders:
        serviceId: guild-service
        stripPrefix: false
    guildMember:
        path: /guildMember/**
        sensitiveHeaders:
        serviceId: guild-service
        stripPrefix: false
    
#Spring Boot Config            
spring:
    profiles:
        active: default
    jackson:
        default-property-inclusion: non_null
        
eureka:         #tells about the Eureka server details and its refresh time
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: ${EUREKASERVER:http://localhost:8761/eureka/}
        healthcheck:
            enabled: true
        lease:
            duration: 5
        
feign:
    hystrix:
        enabled: true
hystrix:
    shareSecurityContext: true
