server:
    port: 9000

management: 
    security: 
        enabled: false
zuul:
  prefix: /idle/api
  routes:
    friend:
        path: /friend/**
        sensitiveHeaders:
        url: http://PLAYER-SERVICE:8085/friend
    actionEffectTypes:
        path: /actionEffectTypes/**
        sensitiveHeaders:
        url: http://HERO-SERVICE:8082/actionEffectTypes
    heroTypes:
        path: /heroTypes/**
        sensitiveHeaders:
        url: http://HERO-SERVICE:8082/heroTypes
    heroTypeTypes:
        path: /heroTypeTypes/**
        sensitiveHeaders:
        url: http://HERO-SERVICE:8082/heroTypeTypes
    heroType:
        path: /heroType/**
        sensitiveHeaders:
        url: http://HERO-SERVICE:8082/heroType
    hero:
        path: /hero/**
        sensitiveHeaders:
        url: http://HERO-SERVICE:8082/hero
    battleHero:
        path: /battleHero/**
        sensitiveHeaders:
        url: http://BATTLE-SERVICE:8081/battleHero
    formation:
        path: /formation/**
        sensitiveHeaders:
        url: http://BATTLE-SERVICE:8081/formation
    user:
        path: /user/**
        sensitiveHeaders:
        url: http://PLAYER-SERVICE:8085/user
    userResource:
        path: /userResource/**
        sensitiveHeaders:
        url: http://PLAYER-SERVICE:8085/userResource
    mail:
        path: /mail/**
        sensitiveHeaders:
        url: http://MAIL-SERVICE:8084/mail
    battle:
        path: /battle/**
        sensitiveHeaders:
        url: http://BATTLE-SERVICE:8081/battle
    shop:
        path: /shop/**
        sensitiveHeaders:
        url: http://SHOP-SERVICE:8086/shop
    chat:
        path: /chat/**
        sensitiveHeaders:
        url: http://CHAT-SERVICE:8083/chat
    pvp:
        path: /pvp/**
        sensitiveHeaders:
        url: http://PLAYER-SERVICE:8085/pvp
    guild:
        path: /guild/**
        sensitiveHeaders:
        url: http://GUILD-SERVICE:8087/guild
    guildMember:
        path: /guildMember/**
        sensitiveHeaders:
        url: http://GUILD-SERVICE:8087/guildMember
    
#Spring Boot Config            
spring:
    profiles:
        active: default
    jackson:
        default-property-inclusion: non_null
        
eureka:         #tells about the Eureka server details and its refresh time
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: ${EUREKASERVER:http://localhost:8761/eureka/}
        healthcheck:
            enabled: true
        lease:
            duration: 5
        
feign:
    hystrix:
        enabled: true
hystrix:
    shareSecurityContext: true
